"""Scaffold a per-case run workspace the agent works in.

Reuses Flash's own ``flash env setup`` scaffold (``cmd_env_setup``) verbatim — so the agent
gets the exact ``environment.py`` / ``configs/`` / ``TRAINING.md`` (the agent playbook) a real
user gets — then overlays the case: the train rows, an algorithm-appropriate config pinned to
the resolved model, and (easy mode) the supplied reward frozen into ``environment.py`` next to
a copied ``reward.py``.

``cmd_env_setup`` writes into the current working directory, so scaffolding briefly chdirs
into the workspace and restores the prior directory in a ``finally``.
"""

from __future__ import annotations

import contextlib
import json
import os
import shutil
from dataclasses import dataclass
from pathlib import Path

from autoenv.manifest import PaperCase
from flash.cli.commands import cmd_env_setup

# Easy-mode environment.py: wraps the frozen, supplied ``reward.score(gold, response)`` into
# the Freesolo RewardResult contract. The reward is imported, never inlined, so it stays the
# fixed signal the agent is told not to touch.
_EASY_ENV_PY = '''\
"""Generated by autoenv for case {case_id} (easy mode: the reward is supplied and frozen).

Do NOT edit reward.py — it is the fixed learning signal for this benchmark case. You may edit
the prompt construction and the training config.
"""

from __future__ import annotations

import json
from pathlib import Path

from freesolo.datasets.types import TaskExample
from freesolo.environments import EnvironmentSingleTurn, RewardMetric, RewardResult

from reward import score as _supplied_score  # frozen supplied reward — do not change

DEFAULT_DATASET_PATH = Path(__file__).parent / "datasets" / "train.jsonl"


def load_jsonl(path):
    rows = []
    with Path(path).open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


class CaseEnv(EnvironmentSingleTurn):
    dataset = load_jsonl(DEFAULT_DATASET_PATH)

    def build_prompt_messages(self, example: TaskExample, prompt_text: str):
        return [{{"role": "user", "content": example.input}}]

    def score_response(self, example: TaskExample, response_text: str) -> RewardResult:
        s = float(_supplied_score(str(example.output or ""), response_text or ""))
        return RewardResult(
            score=s,
            threshold=1.0,
            metrics=(RewardMetric(name="success", score=float(s >= 1.0)),),
        )


def load_environment(dataset_path: str | None = None, **kwargs) -> CaseEnv:
    env = CaseEnv()
    if dataset_path:
        env.dataset = load_jsonl(dataset_path)
    return env
'''


@dataclass(frozen=True)
class Workspace:
    """A scaffolded run workspace for one case."""

    root: Path
    case_id: str
    model_id: str
    algorithm: str
    env_id_placeholder: str

    @property
    def config_path(self) -> Path:
        name = "rl.toml" if self.algorithm == "grpo" else "sft.toml"
        return self.root / "configs" / name

    @property
    def environment_py(self) -> Path:
        return self.root / "environment.py"

    @property
    def train_jsonl(self) -> Path:
        return self.root / "datasets" / "train.jsonl"


@contextlib.contextmanager
def _chdir(path: Path):
    prev = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(prev)


def _write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(
            json.dumps({"input": r.get("input", ""), "output": r.get("output", "")}) + "\n"
            for r in rows
        ),
        encoding="utf-8",
    )


def _config_toml(case: PaperCase, model_id: str, env_id: str) -> str:
    lines = [
        f'model = "{model_id}"',
        f'algorithm = "{case.algorithm}"',
        "",
        "[environment]",
        f'id = "{env_id}"',
        "",
        "[train]",
        "lora_rank = 32",
        "lora_alpha = 64",
        "seeds = [0]",
    ]
    if case.algorithm == "grpo":
        lines.append(f"steps = {case.max_train_steps or 150}")
    else:
        lines.append("epochs = 1")
        if case.max_train_steps:
            lines.append(f"max_steps = {case.max_train_steps}")
        if case.max_train_examples:
            lines.append(f"max_examples = {case.max_train_examples}")
    return "\n".join(lines) + "\n"


def scaffold(
    case: PaperCase,
    dest: str | Path,
    model_id: str,
    *,
    train_rows: list[dict],
) -> Workspace:
    """Create a ready-to-train workspace for ``case`` at ``dest``."""
    root = Path(dest)
    root.mkdir(parents=True, exist_ok=True)

    # 1. Flash's own scaffold (environment.py, datasets/, configs/{rl,sft}.toml, TRAINING.md).
    with _chdir(root):
        cmd_env_setup(_NoArgs())

    # 2. Overlay the case's train rows.
    _write_jsonl(root / "datasets" / "train.jsonl", train_rows)

    env_id = f"autoenv/{case.id}"
    ws = Workspace(
        root=root,
        case_id=case.id,
        model_id=model_id,
        algorithm=case.algorithm,
        env_id_placeholder=env_id,
    )

    # 3. Easy mode: freeze the supplied reward into the environment.
    if case.difficulty == "easy":
        if not case.supplied_reward_path or not Path(case.supplied_reward_path).is_file():
            raise FileNotFoundError(
                f"case {case.id!r}: supplied_reward_path not found: {case.supplied_reward_path}"
            )
        shutil.copyfile(case.supplied_reward_path, root / "reward.py")
        ws.environment_py.write_text(_EASY_ENV_PY.format(case_id=case.id), encoding="utf-8")

    # 4. Pin the config to the resolved model + case caps + placeholder env id.
    ws.config_path.parent.mkdir(parents=True, exist_ok=True)
    ws.config_path.write_text(_config_toml(case, model_id, env_id), encoding="utf-8")
    return ws


class _NoArgs:
    """cmd_env_setup ignores its ``args``; this is a placeholder to satisfy the signature."""
