"""Build-time extractor: pull `_CHILD_CUDART_FIX` out of engine/worker/verl/capabilities.py and
emit it as a standalone script the worker image runs against /opt/verl-venv.

Dockerfile.worker sets FLASH_VERL_PYTHON=/opt/verl-venv/bin/python, and resolve_verl_python returns
a preset interpreter untouched (flash does not own a foreign one), so the repair it applies to the
venv it provisions itself never runs on the prebuilt image. That venv installs tilelang, whose
libcudart stub is the one vLLM aborts its import on. This applies the same repair where that venv is
built instead.

Extracted rather than duplicated: a second copy of the script in the Dockerfile would drift from the
runtime one, and the two must stay identical -- they repair the same venv on different paths.
`_CHILD_CUDART_FIX` is a self-contained module-level string (stdlib only, no flash import, since the
venv it runs in has no flash), so reading its source needs no flash import here either.

Usage: python extract_cudart_fix.py <path-to-capabilities.py> <out-path>
"""

import ast
import sys

CONSTANT = "_CHILD_CUDART_FIX"


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {sys.argv[0]} <path-to-capabilities.py> <out-path>")
    src_path, out_path = sys.argv[1], sys.argv[2]
    with open(src_path, encoding="utf-8") as f:
        src = f.read()

    body = None
    for node in ast.walk(ast.parse(src)):
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == CONSTANT for t in node.targets):
            continue
        # a non-literal assignment (an f-string, a concat) would extract to something that is not
        # what the runtime path runs. fail the build rather than bake a divergent script.
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            body = node.value.value
        break

    if body is None:
        raise SystemExit(f"could not find a literal {CONSTANT} string in {src_path}")
    # the venv this runs in has no flash on its path, so an import that crept in would make the
    # repair a silent no-op -- the exact failure it exists to prevent.
    if "import flash" in body or "from flash" in body:
        raise SystemExit(f"{CONSTANT} imports flash; it must stay stdlib-only to run in the venv")
    ast.parse(body)

    out = (
        f"# AUTO-GENERATED by flash/docker/extract_cudart_fix.py from {CONSTANT} in\n"
        "# flash/engine/worker/verl/capabilities.py. Do not edit; regenerated at image build time.\n"
        + body
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {out_path} ({len(out)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
