"""Build-time generator: extract `_train_body` source from providers/runpod/train/endpoints.py and
emit a standalone RunPod Serverless handler (/rp_handler.py) baked into the worker image.

This makes the worker image a *self-contained RunPod Serverless worker* (Pattern D): when RunPod
Flash deploys it as a custom image (client mode), the baked CMD runs this handler, which reads the
job payload from job["input"] and runs the training via `_train_body`.

`_train_body` imports its trusted verifier from the sibling module baked into the image, then fetches
the pinned Flash source archive from HF.

Usage: python make_rp_handler.py <path-to-endpoints.py> <path-to-archive.py> <out-path>
"""

import ast
import sys


def main() -> int:
    if len(sys.argv) != 4:
        raise SystemExit(
            f"usage: {sys.argv[0]} <path-to-endpoints.py> <path-to-archive.py> <out-path>"
        )
    src_path, verifier_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    fn_src = None
    for node in ast.walk(ast.parse(src)):
        if isinstance(node, ast.FunctionDef) and node.name == "_train_body":
            fn_src = ast.get_source_segment(src, node)
            break
    if not fn_src:
        raise SystemExit("could not find _train_body in " + src_path)
    with open(verifier_path, "rb") as f:
        verifier = f.read()
    ast.parse(verifier, filename=verifier_path)
    out = (
        "# AUTO-GENERATED by flash/docker/make_rp_handler.py from providers/runpod/train/endpoints.py.\n"
        "# Do not edit; the worker image regenerates it at build time.\n"
        "import runpod\n\n" + fn_src + "\n\ndef handler(job):\n"
        '    """RunPod Serverless entry: the job payload is the control plane\'s train input."""\n'
        "    try:\n"
        '        return _train_body(job["input"])\n'
        "    except Exception as exc:\n"
        '        if getattr(exc, "flash_retriable", False):\n'
        '            return {"error": str(exc), "_flash_retriable": True}\n'
        "        raise\n\n"
        'runpod.serverless.start({"handler": handler})\n'
    )
    # Validate it parses before baking.
    ast.parse(out)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {out_path} ({len(out)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
