"""parent-side renderer for the isolated GRPO reward bridge module."""

from __future__ import annotations


def render_reward_module(url_env: str = "FLASH_VERL_REWARD_URL") -> str:
    """render the stdlib-only reward module copied into the verl child."""
    return (
        '"""flash reward bridge shim (generated). posts each completion to the flash worker."""\n'
        "import json\n"
        "import os\n"
        "import urllib.error\n"
        "import urllib.request\n"
        "\n"
        f"_URL = os.environ.get({url_env!r}, '')\n"
        "\n"
        "\n"
        "def compute_score(data_source, solution_str, ground_truth, extra_info=None):\n"
        "    idx = (extra_info or {}).get('index')\n"
        "    if idx is None:\n"
        "        raise RuntimeError('flash reward bridge received no example index')\n"
        "    if not _URL:\n"
        "        raise RuntimeError('flash reward bridge url is not configured')\n"
        "    if isinstance(idx, bool) or getattr(getattr(idx, 'dtype', None), 'kind', None) == 'b':\n"
        "        raise RuntimeError('flash reward bridge received an invalid example index: %r' % idx)\n"
        "    try:\n"
        "        exact_idx = int(idx)\n"
        "    except (TypeError, ValueError, OverflowError) as exc:\n"
        "        raise RuntimeError('flash reward bridge received an invalid example index: %r' % idx) from exc\n"
        "    if exact_idx != idx:\n"
        "        raise RuntimeError('flash reward bridge received an invalid example index: %r' % idx)\n"
        "    idx = exact_idx\n"
        "    body = json.dumps({'index': idx, 'solution_str': solution_str or ''}).encode()\n"
        "    req = urllib.request.Request(\n"
        "        _URL.rstrip('/') + '/score', data=body, headers={'Content-Type': 'application/json'}\n"
        "    )\n"
        "    try:\n"
        "        with urllib.request.urlopen(req) as r:\n"
        "            payload = json.loads(r.read().decode())\n"
        "            return float(payload['score'])\n"
        "    except urllib.error.HTTPError as exc:\n"
        "        detail = ''\n"
        "        try:\n"
        "            detail = str(json.loads(exc.read().decode())['error'])\n"
        "        except Exception:\n"
        "            detail = ''\n"
        "        fault = 'could not serve' if exc.code >= 500 else 'rejected'\n"
        "        if detail:\n"
        "            raise RuntimeError('flash reward bridge %s the request (HTTP %s): %s'\n"
        "                               % (fault, exc.code, detail)) from exc\n"
        "        raise RuntimeError('flash reward bridge %s the request: HTTP %s with no error detail'\n"
        "                           % (fault, exc.code)) from exc\n"
        "    except urllib.error.URLError as exc:\n"
        "        raise RuntimeError('flash reward bridge request failed: %s' % exc) from exc\n"
        "    except Exception as exc:\n"
        "        raise RuntimeError('flash reward bridge returned an invalid response: %s' % exc) from exc\n"
    )
