"""Build and verify runtime capsules.

The archive is a Python zipapp (`.pyz`) rather than a tarball because the far end must be able to
EXECUTE it with nothing but stock Python. A tarball would need an extractor shipped alongside it,
and shipping that extractor as text is the problem this package exists to remove.

Builds are deterministic: fixed mtime, fixed mode, no uid/gid, sorted member order, fixed
compression. Two builds of the same sources produce byte-identical archives on 3.11 and 3.12, so
a digest recorded at image-build time still matches at run time.
"""

from __future__ import annotations

import contextlib
import io
import os
import tempfile
import zipfile
from pathlib import Path

from flash.runtime_capsule.manifest import (
    MANIFEST_NAME,
    CapsuleError,
    Manifest,
    Member,
    parse_manifest,
    sha256_bytes,
    validate_member_path,
    verify_archive_digest,
    verify_members,
)
from flash.runtime_capsule.profiles import Profile, get_profile

# zipapps are executed by the interpreter, which reads __main__.py from the archive root.
_MAIN_NAME = "__main__.py"

# a fixed DOS timestamp (the zip epoch) so the archive bytes do not track when it was built.
_FIXED_DATE_TIME = (1980, 1, 1, 0, 0, 0)
_FIXED_MODE = 0o644

# the shebang a zipapp carries so the file can be executed directly. kept explicit rather than
# using zipapp.create_archive so member order, timestamps, and compression stay under our control.
_SHEBANG = b"#!/usr/bin/env python3\n"

# `__main__` cannot own anything a spawned child must unpickle: multiprocessing's spawn start
# method re-imports the entry as `__mp_main__`, and a target defined in a zipapp's __main__ is
# then unreachable by name. So __main__ only dispatches into a real member module.
#
# it dispatches by NAME because one capsule carries several programs the launch script runs
# separately (the bootstrap plus the host helpers). the runnable set is baked in at build time and
# an unknown name exits non-zero rather than falling back to the entrypoint: silently running the
# wrong program is how a typo'd launch line becomes a training run nobody asked for.
_MAIN_TEMPLATE = """\
# generated by flash.runtime_capsule.build; do not edit.
# this module only dispatches: anything a spawned child must reach by name has to live in a real
# member module, because multiprocessing re-imports the entry under a different module name.
import runpy
import sys

RUNNABLE = {runnable!r}
DEFAULT = {entry_module!r}

argv = sys.argv[1:]
if argv and argv[0].startswith("--run="):
    name, rest = argv[0][len("--run=") :], argv[1:]
elif argv:
    # a bare first argument is ALWAYS a program name, never a program argument. the alternative --
    # treating an unrecognized word as an argument to the default -- means a typo'd or renamed
    # launch line silently starts the training bootstrap on a rented box.
    name, rest = argv[0], argv[1:]
else:
    name, rest = DEFAULT, []
if name not in RUNNABLE:
    sys.exit("flash capsule: unknown program %r (have: %s)" % (name, ", ".join(RUNNABLE)))
target, sys.argv = name, [name, *rest]

runpy.run_module(target, run_name="__main__", alter_sys=True)
"""


def _read_sources(root: Path, profile: Profile) -> dict[str, bytes]:
    """Read a profile's declared sources, keyed by their member path."""
    contents: dict[str, bytes] = {}
    for source, member_path in profile.sources:
        validate_member_path(member_path)
        path = root / source
        if not path.is_file():
            raise CapsuleError(
                f"capsule profile {profile.name!r} declares {source!r}, which does not exist"
            )
        if member_path in contents:
            raise CapsuleError(
                f"capsule profile {profile.name!r} maps two sources to {member_path!r}"
            )
        contents[member_path] = path.read_bytes()
    if profile.entrypoint not in contents:
        raise CapsuleError(
            f"capsule profile {profile.name!r} entrypoint {profile.entrypoint!r} is not one of its sources"
        )
    return contents


def _module_name(path: str, *, what: str) -> str:
    """The importable module name for a top-level capsule member, or raise.

    Members are flat by construction: the far end puts the capsule on `sys.path` and imports them
    as bare top-level modules, exactly as the launch scripts used to write them into one directory.
    """
    if not path.endswith(".py") or "/" in path:
        raise CapsuleError(f"capsule {what} must be a top-level module file, got {path!r}")
    return path[: -len(".py")]


def build_manifest(profile: Profile, contents: dict[str, bytes]) -> Manifest:
    """The manifest describing `contents` for `profile`."""
    members = tuple(
        Member(path=path, size=len(data), sha256=sha256_bytes(data))
        for path, data in sorted(contents.items())
    )
    return Manifest(
        profile=profile.name,
        profile_version=profile.version,
        entrypoint=profile.entrypoint,
        members=members,
    )


def _write_archive(payload: dict[str, bytes]) -> bytes:
    """Pack `payload` into a deterministic zipapp."""
    buffer = io.BytesIO()
    buffer.write(_SHEBANG)
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name in sorted(payload):
            info = zipfile.ZipInfo(name, date_time=_FIXED_DATE_TIME)
            info.external_attr = _FIXED_MODE << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            # create_system is otherwise host-dependent (3 on posix, 0 on windows), which would
            # make the same sources produce different bytes on different builders.
            info.create_system = 3
            archive.writestr(info, payload[name])
    return buffer.getvalue()


def build_capsule(profile_name: str, *, root: Path | None = None) -> tuple[bytes, Manifest]:
    """Build the named profile's capsule from the repository, returning (archive, manifest)."""
    profile = get_profile(profile_name)
    repo_root = root if root is not None else Path(__file__).resolve().parents[2]
    contents = _read_sources(repo_root, profile)
    manifest = build_manifest(profile, contents)

    entry_module = _module_name(profile.entrypoint, what="entrypoint")
    runnable = tuple(sorted(_module_name(path, what="member") for path in contents))

    payload = dict(contents)
    payload[MANIFEST_NAME] = manifest.to_json().encode("utf-8")
    payload[_MAIN_NAME] = _MAIN_TEMPLATE.format(
        entry_module=entry_module, runnable=runnable
    ).encode("utf-8")
    return _write_archive(payload), manifest


def read_capsule(archive: bytes) -> tuple[Manifest, dict[str, bytes]]:
    """Parse an archive and verify it against its own manifest.

    This proves internal consistency only. It does NOT prove the capsule is ours -- pair it with
    `verify_capsule`, which binds an externally supplied digest.
    """
    try:
        with zipfile.ZipFile(io.BytesIO(archive)) as zf:
            infos = zf.infolist()
            names = [i.filename for i in infos]
            if len(set(names)) != len(names):
                raise CapsuleError("capsule archive contains duplicate member names")
            for info in infos:
                # a directory entry or a symlink can redirect a later write outside the tree; a
                # capsule is a flat set of regular files and needs neither.
                if info.is_dir():
                    raise CapsuleError(
                        f"capsule archive contains a directory entry: {info.filename!r}"
                    )
                if (info.external_attr >> 16) & 0o170000 == 0o120000:
                    raise CapsuleError(f"capsule archive contains a symlink: {info.filename!r}")
                validate_member_path(info.filename)
            if MANIFEST_NAME not in names:
                raise CapsuleError(f"capsule archive has no {MANIFEST_NAME}")
            payload = {name: zf.read(name) for name in names}
    except zipfile.BadZipFile as exc:
        raise CapsuleError(f"capsule archive is not a readable zip: {exc}") from exc

    manifest = parse_manifest(payload[MANIFEST_NAME])
    contents = {
        name: data for name, data in payload.items() if name not in {MANIFEST_NAME, _MAIN_NAME}
    }
    verify_members(manifest, contents)
    return manifest, contents


def verify_capsule(
    archive: bytes,
    *,
    expected_sha256: str,
    expected_profile: str | None = None,
) -> Manifest:
    """Fully verify an archive: external digest first, then contents.

    The digest is checked BEFORE the archive is parsed. Parsing an unverified archive is the
    first place attacker-controlled bytes reach a decoder, so the cheap check that can reject
    them outright runs first.
    """
    verify_archive_digest(archive, expected_sha256)
    manifest, _contents = read_capsule(archive)
    if expected_profile is not None and manifest.profile != expected_profile:
        raise CapsuleError(
            f"capsule profile mismatch: expected {expected_profile!r}, got {manifest.profile!r}"
        )
    return manifest


def write_capsule(destination: Path, archive: bytes) -> None:
    """Write an archive to `destination` atomically and executably."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=destination.parent, prefix=".flash-capsule-")
    os.close(fd)
    try:
        Path(tmp).write_bytes(archive)
        os.chmod(tmp, 0o755)
        os.replace(tmp, destination)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise
